services:
  web-app:
    build: 
      context: ./web-app
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - ./web-app/.env 
    environment:
      - MONGO_CXN_STRING
      - ML_CLIENT_PORT=http://ml-client:5002
    depends_on:
      - ml-client

  ml-client:
    build:
      context: ./machine-learning-client
      dockerfile: Dockerfile
    ports:
      - "5002:5002"

networks:
  default:
    driver: bridge