name: Machine Learning Client CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'machine-learning-client/**'

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./machine-learning-client

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev

      - name: Run tests
        run: |
          pipenv run coverage run -m pytest
          pipenv run coverage report

      - name: Build Docker image
        run: |
          docker build -t ml-client .